---

- hosts: playground
  become: true
  become_user: root

  roles:
    - common
    - Stouts.nginx
    - ANXS.postgresql
    - webserver

  vars:
    web_user: web
    web_virtualenv: /var/venv/playground
    supervisor_incdir: /etc/supervisor/conf.d
    python_versions: [3.5]
    python_virtualenvs:
      - path: "{{ web_virtualenv }}"
        python: python3.5

    postgresql_version: 9.5
    postgresql_ext_install_dev_headers: yes
    postgresql_databases:
      - name: playground
